#!/bin/python3

import math
import os
import random
import re
import sys


# The function is expected to return an INTEGER_ARRAY.
# The function accepts following parameters:
#  1. INTEGER_ARRAY a
#  2. INTEGER_ARRAY b
#

def compareTriplets(a, b):
    # Write your code here
    aScore=0
    bScore=0
    for index in range(len(a)):
        if a[index]<b[index]:
            bScore+=1
        elif a[index]>b[index]:
            aScore+=1
           
    return[aScore,bScore]               

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    a = list(map(int, input().rstrip().split()))

    b = list(map(int, input().rstrip().split()))

    result = compareTriplets(a, b)

    fptr.write(' '.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
